/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as SendRouteImport } from './routes/send'
import { Route as SendIndexRouteImport } from './routes/send.index'
import { Route as SendConfirmRouteImport } from './routes/send.confirm'
import { Route as SendPinRouteImport } from './routes/send.pin'
import { Route as SendSuccessRouteImport } from './routes/send.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const SendIndexRoute = SendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SendRoute,
} as any)
const SendConfirmRoute = SendConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => SendRoute,
} as any)
const SendPinRoute = SendPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => SendRoute,
} as any)
const SendSuccessRoute = SendSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SendRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/send': typeof SendRouteWithChildren
  '/send/confirm': typeof SendConfirmRoute
  '/send/pin': typeof SendPinRoute
  '/send/success': typeof SendSuccessRoute
  '/send/': typeof SendIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/send/confirm': typeof SendConfirmRoute
  '/send/pin': typeof SendPinRoute
  '/send/success': typeof SendSuccessRoute
  '/send': typeof SendIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/send': typeof SendRouteWithChildren
  '/send/confirm': typeof SendConfirmRoute
  '/send/pin': typeof SendPinRoute
  '/send/success': typeof SendSuccessRoute
  '/send/': typeof SendIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/discover'
    | '/send'
    | '/send/confirm'
    | '/send/pin'
    | '/send/success'
    | '/send/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/discover'
    | '/send/confirm'
    | '/send/pin'
    | '/send/success'
    | '/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/discover'
    | '/send'
    | '/send/confirm'
    | '/send/pin'
    | '/send/success'
    | '/send/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DiscoverRoute: typeof DiscoverRoute
  SendRoute: typeof SendRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send/': {
      id: '/send/'
      path: '/'
      fullPath: '/send/'
      preLoaderRoute: typeof SendIndexRouteImport
      parentRoute: typeof SendRoute
    }
    '/send/confirm': {
      id: '/send/confirm'
      path: '/confirm'
      fullPath: '/send/confirm'
      preLoaderRoute: typeof SendConfirmRouteImport
      parentRoute: typeof SendRoute
    }
    '/send/pin': {
      id: '/send/pin'
      path: '/pin'
      fullPath: '/send/pin'
      preLoaderRoute: typeof SendPinRouteImport
      parentRoute: typeof SendRoute
    }
    '/send/success': {
      id: '/send/success'
      path: '/success'
      fullPath: '/send/success'
      preLoaderRoute: typeof SendSuccessRouteImport
      parentRoute: typeof SendRoute
    }
  }
}

interface SendRouteChildren {
  SendConfirmRoute: typeof SendConfirmRoute
  SendPinRoute: typeof SendPinRoute
  SendSuccessRoute: typeof SendSuccessRoute
  SendIndexRoute: typeof SendIndexRoute
}

const SendRouteChildren: SendRouteChildren = {
  SendConfirmRoute: SendConfirmRoute,
  SendPinRoute: SendPinRoute,
  SendSuccessRoute: SendSuccessRoute,
  SendIndexRoute: SendIndexRoute,
}

const SendRouteWithChildren = SendRoute._addFileChildren(SendRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DiscoverRoute: DiscoverRoute,
  SendRoute: SendRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
